# tasks file for zoneminder
- name: load settings
  include_vars: settings/zoneminder.yml

- name: add install/update hook
  ansible.builtin.copy:
    src: custom-zoneminder-post.hook
    dest: "{{hookDir}}"
  become: true

- name: change ownership of storage dir
  ansible.builtin.file:
    path: "{{ zmDir }}"
    owner: "{{ zmOwner }}"
    group: "{{ zmGroup }}"
  become: true
