# tasks file for firefox
- name: install
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  with_items: "{{ packages }}"
  become: true
- name: create local launcher file
  ansible.builtin.template:
    src: firefox.desktop
    dest: "{{userDir}}/.local/share/applications"
- name: create config dir
  ansible.builtin.file:
    path: "{{configDir}}"
    state: directory
- name: look for config backup
  ansible.builtin.stat:
    path: "{{backupDir}}"
  register: st
- name: recover config
  ansible.builtin.synchronize:
    src: "{{backupDir}}"
    dest: "{{configDir}}"
  when: st.stat.isdir is defined
