# tasks file for bash
- name: source dotbashrc in .bashrc
  ansible.builtin.lineinfile:
    path: "{{userDir}}/.bashrc"
    line: ". {{userDir}}/Scripts/dotbashrc"
    insertbefore: EOF
    state: present
