# tasks file for bash
- name: load settings
  include_vars: settings/bash.yml

- name: source dotbashrc in .bashrc
  ansible.builtin.lineinfile:
    path: "{{userDir}}/.bashrc"
    line: ". {{dropboxLinuxDir}}/Scripts/dotbashrc"
    insertbefore: EOF
    state: present
