# tasks file for sudoers
- name: add entries to sudoers
  ansible.builtin.lineinfile:
    path: "{{sudoers}}"
    line: "{{item}}"
    state: present
    mode:  0600
    create: yes
  with_items: "{{lines}}"
  become: true
