# tasks for power
- name: load settings
  include_vars: settings/power.yml

# https://www.tecmint.com/disable-suspend-and-hibernation-in-linux/

# Verify:
#   systemctl status sleep.target suspend.target hibernate.target hybrid-sleep.target | grep Loaded

- name: Disable suspend and hibernation
  ansible.builtin.systemd:
    name: "{{item}}"
    masked: yes
  with_items: "{{suspend_hibernate_targets}}"
  become: true
