# tasks file for vscode
- name: load settings
  include_vars: settings/vscode.yml

- name: install with dependencies
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  with_items: "{{packages}}"
  become: true

- name: attempt to recover config
  include_role:
    name:       archive
    tasks_from: restore

- name: look for extension list
  ansible.builtin.stat:
    path: "{{extList}}"
  register: st
  
- block:
  - name: Load extensions list from backup
    ansible.builtin.include_vars:
      file: "{{extList}}"
  - name: install extensions
    ansible.builtin.command: "code --install-extension {{item}}"
    register: result
    changed_when: '"successfully installed" in result.stdout'
    with_items: "{{extensions}}"
  - name: remove extention list
    ansible.builtin.file:
      path: "{{extList}}"
      state: absent
  when: st.stat.exists

- name: create local launcher file (specifies the workspace)
  ansible.builtin.template:
    src: code-oss.desktop
    dest: "{{localLauncherDir}}"
