# tasks file for gnome backup

- name: create backup dir
  ansible.builtin.file:
    path: "{{backupDir}}"
    state: directory

- name: make the backups
  ansible.builtin.shell:
    cmd: "dconf dump {{item.path}} > {{backupDir}}/{{item.file}}"
  with_items: "{{backups}}"
