# tasks file for gnome backup

- name: create temp dir
  ansible.builtin.file:
    path: "{{tempDir}}"
    state: directory

- name: make the files
  ansible.builtin.shell:
    cmd: "dconf dump {{item.path}} > {{tempDir}}/{{item.file}}"
  with_items: "{{files}}"

- name: create the archive
  include_role:
    name: "{{mainBackupDir}}/roles/archive"
    tasks_from: create

- name: remove temp dir
  ansible.builtin.file:
    path: "{{tempDir}}"
    state: absent
