# tasks file for cron
- name: load settings
  include_vars: settings/cron.yml

- name: configure service
  ansible.builtin.service:
    name: "{{service_name}}"
    state: "{{service_state}}"
    enabled: "{{service_enabled}}"
  become: true
