# tasks file for novpn
- name: load settings
  include_vars: settings/novpn.yml

# Creates a namespace outside of vpn

- name: add entry for novpn to sudoers
  ansible.builtin.lineinfile:
    path: "{{sudoers}}"
    line: "{{sudoersLine}}"
    state: present
    create: yes
  become: true

- name: install service start/stop scripts
  ansible.builtin.template:
    src: "{{item}}"
    dest: "{{service.scriptsDir}}"
    mode: 0755
  with_items:
  - "{{service.scriptStart}}"
  - "{{service.scriptStop}}"
  become: true

- name: install service
  ansible.builtin.template:
    src: "{{service.name}}.service"
    dest: "{{service.installDir}}"
    mode: 0644
  become: true
  
- name: enable and start
  ansible.builtin.systemd:
    name:  "{{service.name}}"
    state: started
    enabled: yes
  become: true

- name: create local app launchers
  ansible.builtin.template:
    src:  "{{item}}"
    dest: "{{localLauncherDir}}"
  with_items: "{{launchers}}"
