# Defaults for services
services:
- { name: lvm2-monitor,          state: stopped, enabled: no, masked: yes }
- { name: flatpak-system-helper, state: stopped, enabled: no, masked: yes }
#- { name: docker, state: stopped, enabled: no, masked: yes }
#- { name: docker.socket, state: stopped, enabled: no, masked: yes }
#- { name: wpa_supplicant, state: stopped, enabled: no, masked: yes }
