# tasks file for fstrim
- name: load settings
  include_vars: settings/fstrim.yml

- name: timer start
  ansible.builtin.systemd:
    name:  "{{serviceName}}"
    state: "{{serviceState}}"
    enabled: "{{serviceEnabled}}"
  become: true
