# tasks file for sshd
- name: load settings
  include_vars: settings/ssh.yml

- name: install .ssh files
  ansible.builtin.copy:
    src: "{{item}}"
    dest: "{{userDir}}/.ssh"
  with_items: "{{sshfiles}}"
  
- name: enable and start
  ansible.builtin.systemd:
    name:  "{{service}}"
    state: started
    enabled: yes
  become: true

