# tasks file for transmission
- name: load settings
  include_vars: settings/transmission.yml

- name: install
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  with_items: "{{packages}}"
  become: true

- name: attempt to recover config
  include_role:
    name:       archive
    tasks_from: restore
