# tasks file for transmission
- name: install
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  with_items: "{{packages}}"
  become: true

- name: load backup vars
  include_vars: "{{mainBackupDir}}/roles/transmission/defaults/main.yml"
- name: attempt to recover config
  include_role:
    name: "{{mainBackupDir}}/roles/archive"
    tasks_from: restore
