# tasks file for gnome
- name: load settings
  include_vars: settings/gnome.yml


- name: load backup vars
  include_vars: "{{mainBackupDir}}/roles/gnome/defaults/main.yml"
- name: attempt to recover config
  include_role:
    name: "{{mainBackupDir}}/roles/archive"
    tasks_from: restore

- name: load settings
  include_tasks: load.yml
  loop_control:
    label: "{{ item.path }}"
  loop:
    "{{files}}"

- name: remove temp dir
  ansible.builtin.file:
    path: "{{tempDir}}"
    state: absent
