# tasks file for gnome

- name: look for config backup
  ansible.builtin.stat:
    path: "{{backupDir}}"
  register: st

- name: recover config
  ansible.builtin.shell:
    cmd: "dconf load {{item.path}} < {{backupDir}}/{{item.file}}"
  with_items: "{{backups}}"
  when: st.stat.isdir is defined
