# tasks file for gnome
- name: load settings
  include_vars: settings/gnome.yml

- name: attempt to recover config
  include_role:
    name:       archive
    tasks_from: restore

- name: load settings
  include_tasks: load.yml
  loop_control:
    label: "{{ item.path }}"
  loop:
    "{{files}}"

- name: remove temp dir
  ansible.builtin.file:
    path: "{{tempDir}}"
    state: absent
