# tasks file for vscode backup

- name: get extension list
  ansible.builtin.shell:
    cmd: "echo \"# List of extensions for vscode\nextensions:\" ; code --list-extensions | sed -e 's/^/- \"/' -e 's/$/\"/'"
  register: out
  changed_when: false

- name: create formatted extension list
  ansible.builtin.copy:
    content: "{{out.stdout}}"
    dest:    "{{extList}}"

- name: create the archive
  include_role:
    name: "{{mainBackupDir}}/roles/archive"
    tasks_from: create

- name: remove extention list
  ansible.builtin.file:
    path: "{{extList}}"
    state: absent
