# tasks file for novpn
# Creates a namespace outside of vpn
- name: install scripts
  ansible.builtin.template:
    src: "{{item}}"
    dest: "{{service.scriptsDir}}"
    mode: 0755
  with_items:
  - "{{service.scriptStart}}"
  - "{{service.scriptStop}}"
  become: true

- name: install service
  ansible.builtin.template:
    src: "{{service.name}}.service"
    dest: "{{service.installDir}}"
    mode: 0644
  become: true
  
- name: enable and start
  ansible.builtin.systemd:
    name:  "{{service.name}}"
    state: started
    enabled: yes
  become: true
