# tasks file for smb
- name: load settings
  include_vars: settings/smb.yml

- name: install
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  with_items: "{{packages}}"
  become: true
  register: s

- name: get main password
  ansible.builtin.set_fact:
    password: "{{ lookup('env', 'password') }}"

- name: set samba password for main user
  ansible.builtin.shell: "printf '{{ password }}\n{{ password }}\n' | smbpasswd -a {{ user }}"
  become: true
  when: s.changed

- name: add user to group
  ansible.builtin.user:
    name: "{{user}}"
    groups: "{{group}}"
    append: yes
  become: true

- name: configure samba shares
  ansible.builtin.template:
    src: smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - restart smb

