# tasks file for packages
- name: load settings
  include_vars: settings/services.yml

- name: configure service
  ansible.builtin.systemd:
    name:    "{{ item.name }}"
    state:   "{{ item. state }}"
    enabled: "{{ item. enabled }}"
    masked:  "{{ item. masked }}"
  with_items: "{{ services }}"
  become: true
  